const KEY='assetnote-v2';
const OLD_KEY='assetnote-v1';
const seed={assets:[{id:'a1',name:'신한',active:true},{id:'a2',name:'카뱅',active:true},{id:'a3',name:'K뱅',active:true},{id:'a4',name:'사이다(sbi)',active:true},{id:'a5',name:'국민',active:true},{id:'a6',name:'지역화폐 및 현금',active:true}],snapshots:[],incomes:[]};
let db=load(), year=new Date().getFullYear(), expanded={};
function load(){try{const cur=localStorage.getItem(KEY);if(cur)return JSON.parse(cur);const old=localStorage.getItem(OLD_KEY);if(old){const d=JSON.parse(old);localStorage.setItem(KEY,JSON.stringify(d));return d}return seed}catch{return seed}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
const won=n=>new Intl.NumberFormat('ko-KR').format(Math.round(Number(n)||0))+'원';
const num=n=>new Intl.NumberFormat('ko-KR').format(Math.round(Number(n)||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function snapTotal(s){return Object.values(s?.balances||{}).reduce((a,b)=>a+(Number(b)||0),0)}
function sortedSnaps(){return [...db.snapshots].sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id))}
function incomesIn(y){return db.incomes.filter(x=>x.date.startsWith(String(y)+'-')).reduce((a,x)=>a+Number(x.amount||0),0)}
function monthIncome(y,m){return db.incomes.find(x=>x.date.startsWith(`${y}-${String(m).padStart(2,'0')}-`))}
function monthly(y){
 const all=sortedSnaps(), inYear=all.filter(s=>s.date.startsWith(String(y)+'-')), by={};
 inYear.forEach(s=>{const m=s.date.slice(0,7);(by[m]??=[]).push(s)});
 return Object.keys(by).sort().map(m=>{const recs=by[m].sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id)),end=recs[recs.length-1],idx=all.findIndex(s=>s.id===end.id),prev=idx>0?all[idx-1]:null;
   const inc=Number(monthIncome(y,Number(m.slice(5)))?.amount||0),change=prev==null?null:snapTotal(end)-snapTotal(prev),spend=change==null?null:inc-change;
   const latest=end.id===all[all.length-1]?.id,status=latest?'progress':'done'; return {month:m,recs,end,prev,inc,change,spend,status};
 })
}
function annual(y){const ms=monthly(y), latest=sortedSnaps().filter(s=>s.date.startsWith(String(y)+'-')).sort((a,b)=>b.date.localeCompare(a.date))[0];return {income:incomesIn(y),spend:ms.filter(x=>x.spend!=null).reduce((a,x)=>a+x.spend,0),latest}}
function render(){const a=annual(year),ms=monthly(year),latest=a.latest;document.getElementById('app').innerHTML=`
<header class="top"><div><div class="brand">자산노트</div><div class="sub">내 돈의 흐름을 기록하고 관찰합니다.</div></div><div class="actions"><button class="btn secondary" id="assetBtn">자산 관리</button><button class="btn secondary" id="exportBtn">내보내기</button><button class="btn secondary" id="importBtn">가져오기</button></div></header>
<div class="yearnav"><button class="iconbtn" id="prevY">‹</button><div class="year">${year}년</div><button class="iconbtn" id="nextY">›</button></div>
<section class="summary" style="margin-top:12px"><div class="card"><div class="label">올해 수입</div><div class="money">${won(a.income)}</div></div><div class="card"><div class="label">올해 지출</div><div class="money">${won(a.spend)}</div></div><div class="card"><div class="label">현재 가진돈</div><div class="money">${latest?won(snapTotal(latest)):'—'}</div></div></section>
<div class="sectionhead"><div class="sectiontitle">월별 흐름</div><button class="btn primary" id="addBtn">＋ 기록</button></div>
<section class="card timeline">${renderMonths(ms)}</section>`;bind()}
function renderMonths(ms){let rows='';for(let m=12;m>=1;m--){const key=`${year}-${String(m).padStart(2,'0')}`,x=ms.find(v=>v.month===key);if(!x){rows+=`<div class="monthrow"><div><div class="mname">${m}월</div></div><div class="num" style="color:#9ca3af">기록 없음</div><div></div><div></div><div class="status empty">공백</div></div>`;continue}const open=expanded[key];rows+=`<div class="month"><div class="monthrow clickable" data-month="${key}"><div><div class="mname">${m}월</div><div class="date">${x.end.date.slice(5)}</div></div><div class="num"><span class="small">가진돈</span>${num(snapTotal(x.end))}원</div><div class="num"><span class="small">수입</span>${x.inc?num(x.inc)+'원':'—'}</div><div class="num"><span class="small">지출</span>${x.spend==null?'—':num(x.spend)+'원'}</div><div class="status ${x.status==='done'?'done':'progress'}">${x.status==='done'?'확정':'진행 중'}</div></div>${open?detail(x):''}</div>`}return rows}
function detail(x){const income=monthIncome(year,Number(x.month.slice(5)));return `<div class="detail">${x.recs.map(s=>`<div class="record"><div class="recordtop"><b>${s.date}</b><span>${won(snapTotal(s))}</span></div><div class="assetgrid">${Object.entries(s.balances||{}).map(([id,v])=>{const aa=db.assets.find(a=>a.id===id);return aa&&aa.active!==false?`<div class="assetpill"><span>${esc(aa.name)}</span><b>${num(v)}원</b></div>`:''}).join('')}</div>${s.memo?`<div class="memo">${esc(s.memo)}</div>`:''}</div>`).join('')}${income?`<div class="incomeLine">이번 달 수입 · ${esc(income.type)} · ${won(income.amount)} · ${income.date}</div>`:`<div class="incomeLine" style="background:#f9fafb;color:#6b7280">이번 달 수입 기록 없음</div>`}${x.prev?`<div class="notice">분석 구간: ${x.prev.date} → ${x.end.date}${x.status==='progress'?' · 현재 진행 중':''}</div>`:`<div class="notice">이 연도의 첫 자산 기록이라 이전 자산 기준이 없어 지출은 계산하지 않습니다.</div>`}<div class="formactions"><button class="btn mini" data-add-income="${x.month}">＋ 이번 달 수입</button></div></div>`}
function bind(){document.getElementById('addBtn').onclick=()=>openSnapshot();document.getElementById('assetBtn').onclick=openAssets;document.getElementById('prevY').onclick=()=>{year--;render()};document.getElementById('nextY').onclick=()=>{year++;render()};document.querySelectorAll('[data-month]').forEach(e=>e.onclick=()=>{expanded[e.dataset.month]=!expanded[e.dataset.month];render()});document.querySelectorAll('[data-add-income]').forEach(e=>e.onclick=()=>openIncome(e.dataset.addIncome));document.getElementById('exportBtn').onclick=exportData;document.getElementById('importBtn').onclick=importData}
function openSnapshot(){const active=db.assets.filter(a=>a.active!==false),prev=sortedSnaps().at(-1),today=new Date().toISOString().slice(0,10);document.getElementById('modal').innerHTML=`<h2>자산 기록</h2><div class="notice">빈칸은 변경하지 않음 · 0은 실제 0원입니다. 수입은 같은 달에 한 번만 기록합니다.</div><div class="formrow"><div class="field"><label>날짜</label><input id="sdate" type="date" value="${today}"></div><div class="field"><label>메모</label><input id="smemo" placeholder="선택사항"></div></div><div class="field"><label>자산</label>${active.map(a=>`<div class="assetinput"><span style="padding:10px 4px">${esc(a.name)}</span><input data-asset="${a.id}" inputmode="numeric" placeholder="${prev&&prev.balances[a.id]!=null?num(prev.balances[a.id]):''}"></div>`).join('')}</div><div class="field"><label>이번 달 수입 (선택)</label><input id="sincome" inputmode="numeric" placeholder="${monthIncome(Number(today.slice(0,4)),Number(today.slice(5,7)))?'이번 달 수입이 이미 기록됨':'0'}" ${monthIncome(Number(today.slice(0,4)),Number(today.slice(5,7)))?'disabled':''}></div><div class="formactions"><button class="btn" id="cancel">취소</button><button class="btn primary" id="saveSnap">저장</button></div>`;openModal();document.getElementById('cancel').onclick=closeModal;document.getElementById('saveSnap').onclick=()=>{const date=document.getElementById('sdate').value;if(!date)return;const balances={...(prev?.balances||{})};document.querySelectorAll('[data-asset]').forEach(i=>{if(i.value!=='')balances[i.dataset.asset]=Number(i.value.replaceAll(',',''))||0});db.snapshots.push({id:crypto.randomUUID(),date,balances,memo:document.getElementById('smemo').value});const iv=document.getElementById('sincome');if(iv&&!iv.disabled&&iv.value.trim()){const amount=Number(iv.value.replaceAll(',',''));if(amount>0)db.incomes.push({id:crypto.randomUUID(),date,type:'급여',amount})}db.snapshots.sort((a,b)=>a.date.localeCompare(b.date));save();closeModal();year=Number(date.slice(0,4));toast('기록을 저장했습니다');render()}}
function openIncome(month){const [y,m]=month.split('-').map(Number),existing=monthIncome(y,m);if(existing){toast('이 달의 수입은 이미 기록되어 있습니다');return}const date=`${month}-01`;document.getElementById('modal').innerHTML=`<h2>${m}월 수입</h2><div class="notice">수입은 한 달에 한 번만 기록합니다. 종류와 금액을 입력하면 해당 월에 표시됩니다.</div><div class="formrow"><div class="field"><label>날짜</label><input id="idate" type="date" value="${date}"></div><div class="field"><label>종류</label><input id="itype" value="급여"></div></div><div class="field"><label>금액</label><input id="iamount" inputmode="numeric" placeholder="0"></div><div class="formactions"><button class="btn" id="cancel">취소</button><button class="btn primary" id="saveIncome">저장</button></div>`;openModal();document.getElementById('cancel').onclick=closeModal;document.getElementById('saveIncome').onclick=()=>{const amount=Number(document.getElementById('iamount').value.replaceAll(',',''));if(!amount)return;db.incomes.push({id:crypto.randomUUID(),date:document.getElementById('idate').value,type:document.getElementById('itype').value||'기타',amount});save();closeModal();toast('수입을 저장했습니다');render()}}
function openAssets(){document.getElementById('modal').innerHTML=`<h2>자산 관리</h2><div class="notice">자산 이름은 자유롭게 만들 수 있습니다. 삭제 대신 비활성화하면 기존 기록의 이름은 보존됩니다.</div><div id="assetList">${db.assets.map(a=>`<div class="manageAsset"><div class="name">${esc(a.name)}${a.active===false?' · 비활성':''}</div><div><button class="btn mini" data-toggle="${a.id}">${a.active===false?'복원':'삭제'}</button></div></div>`).join('')}</div><div class="field" style="margin-top:14px"><label>새 자산</label><div class="assetinput"><input id="newAsset" placeholder="예: 삼성증권"><button class="btn primary" id="addAsset">추가</button></div></div><div class="formactions"><button class="btn primary" id="closeAssets">닫기</button></div>`;openModal();document.getElementById('closeAssets').onclick=closeModal;document.getElementById('addAsset').onclick=()=>{const name=document.getElementById('newAsset').value.trim();if(!name)return;if(db.assets.some(a=>a.name===name&&a.active!==false)){toast('같은 이름의 자산이 있습니다');return}db.assets.push({id:crypto.randomUUID(),name,active:true});save();openAssets()};document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const a=db.assets.find(x=>x.id===b.dataset.toggle);if(a){a.active=a.active===false;save();openAssets()}})}
function openModal(){document.getElementById('modalBack').classList.add('open')}function closeModal(){document.getElementById('modalBack').classList.remove('open')}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`assetnote-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=()=>{const f=i.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d.assets||!d.snapshots||!d.incomes)throw 0;db=d;save();render();toast('가져왔습니다')}catch{toast('올바른 자산노트 파일이 아닙니다')}};r.readAsText(f)};i.click()}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=2').then(r=>r.update());
